### ISSUE TITLE
Unable to load the map

### ISSUE THREAD

**Issue by abhisek176** [echaussidon/desi_ec#1]
Hi,

Can you please give some instructions to load the DESI map? Is it possible to load specific paintings on the map? I have attached one example plot?

Also,  Is it possible to import ALADIN MOC maps for any given surveys?

Thanks a lot.

[-Abhisek[](url)](url
![Screenshot from 2022-03-29 19-11-11](https://user-images.githubusercontent.com/21282927/160624813-b3d7917c-7f9f-4e2c-852f-231a4983c0fc.png)
)

**Comment by echaussidon** [comment]
Hi (I just saw your issue),

I have only a DESI legacy footprint as a HEALPix map at nside 256. It is here : data/Legacy_imaging_DR9_footprint_256.fits. 

You can just load it and use healpy routine to plot it in mollweide projection. To over plot some information on it, you should use the same routine (https://healpy.readthedocs.io/en/latest/generated/healpy.visufunc.mollview.html#healpy.visufunc.mollview) but collect the output and plot it in a specific axe with matplotlib and then plot something on it. 

Have a look here : https://github.com/echaussidon/desi_ec/blob/0bd06ec2720ac9634452c387d4d343f7d5af0030/plot.py#L155
